# Site settings
title: del caos
email: brian.hochhalter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  User experience, education, innovation, and management according to Brian Hochhalter
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brianhoch.github.io" # the base hostname & protocol for your site
twitter_username: brianhoch
github_username:  brianhoch

# Build settings
markdown: kramdown
